_format_version: "2.1"

services:

- name: echo-server
  url: http://192.168.63.100:6969
  routes:
  - name: echo
    paths:
    - /echo

plugins:

- name: proxy-cache
  config: 
    response_code:
    - 200
    request_method:
    - GET
    - HEAD
    content_type:
    - text/plain
    - application/json
    - application/json; charset=utf-8
    cache_ttl: 300
    strategy: memory

- name: bot-detection
  config:
    deny:
#    - "(C|c)hrome"
    - "curl"

- name: cors
  config: 
    origins:
    - '*'
    methods:
    - GET
    - POST
    headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - X-Auth-Token
    - Authorization
    exposed_headers:
    - X-Auth-Token
    credentials: true
    max_age: 3600
    preflight_continue: false

- name: rate-limiting
  config: 
#    second: 5
    hour: 10
    policy: local
    fault_tolerant: true
    hide_client_headers: false
    redis_ssl: false
    redis_ssl_verify: false
# comment these if you don't want to store rate limiting data in redis
#    policy: redis
#    redis_host: 172.27.59.36
#    redis_password: example

- name: ip-restriction
  config: 
    deny:
    - 172.28.64.0/24
    status: 401
    message: cannot grant access
